name: Discord Notification

on: [push, pull_request]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Description
      id: set_description
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo "DESCRIPTION=A new commit has been pushed to ${{ github.ref }}"
        elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "DESCRIPTION=A pull request has been ${GITHUB_EVENT.pull_request.action} in the repository"
        fi
      env:
        GITHUB_EVENT: ${{ toJson(github.event) }}

    - name: Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        title: "${{ github.workflow }} - ${{ job.status }}"
        description: ${{ steps.set_description.outputs.DESCRIPTION }}
        color: 0x0000ff
        url: ${{ github.event.repository.html_url }}
        username: "GitHub Actions"
        avatar_url: "https://github.com/${{ github.actor }}.png"
