name: Discord Notification

on: [push, pull_request]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@0.3.2
      with:
        args: >
          {
            "embeds": [
              {
                "title": "Deployment Status",
                "description": "The project ${{ github.repository }} has been deployed successfully.",
                "color": 5814783,
                "fields": [
                  {
                    "name": "Branch",
                    "value": "${{ github.ref_name }}"
                  },
                  {
                    "name": "Action Triggered By",
                    "value": "${{ github.actor }}"
                  }
                ],
                "author": {
                  "name": "${{ github.actor }}",
                  "icon_url": "https://github.com/${{ github.actor }}.png"
                },
                "timestamp": "${{ github.event.head_commit.timestamp }}"
              }
            ]
          }
