name: Discord Notification

on: [push, pull_request]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@0.3.2
      with:
        args: '{"embeds": [{"title": "Deployment Status", "description": "The project ${GITHUB_REPOSITORY} has been deployed successfully.", "color": 5814783, "fields": [{"name": "Branch", "value": "${GITHUB_REF_NAME}"}, {"name": "Action Triggered By", "value": "${GITHUB_ACTOR}"}], "author": {"name": "${GITHUB_ACTOR}", "icon_url": "https://github.com/${GITHUB_ACTOR}.png"}, "timestamp": "${{ github.event.head_commit.timestamp }}"}]}'
